// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4wUBKjUkxhhmHyQTBOgcFuiQz3fKWU90',
    appId: '1:696785694778:web:0088104ad86f43c19d8503',
    messagingSenderId: '696785694778',
    projectId: 'fir-flutter-cdoelab',
    authDomain: 'fir-flutter-cdoelab.firebaseapp.com',
    storageBucket: 'fir-flutter-cdoelab.firebasestorage.app',
    measurementId: 'G-0622BHTKNB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCabV17Nw_V4fKMZdTP8RLV5JjhbamHPQQ',
    appId: '1:696785694778:android:ed9770e7c2120d339d8503',
    messagingSenderId: '696785694778',
    projectId: 'fir-flutter-cdoelab',
    storageBucket: 'fir-flutter-cdoelab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbe3tVCbHG3FaNwWTHstl6P5bo5Cvi1uM',
    appId: '1:696785694778:ios:6374d2e2476f4c5b9d8503',
    messagingSenderId: '696785694778',
    projectId: 'fir-flutter-cdoelab',
    storageBucket: 'fir-flutter-cdoelab.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbe3tVCbHG3FaNwWTHstl6P5bo5Cvi1uM',
    appId: '1:696785694778:ios:6374d2e2476f4c5b9d8503',
    messagingSenderId: '696785694778',
    projectId: 'fir-flutter-cdoelab',
    storageBucket: 'fir-flutter-cdoelab.firebasestorage.app',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
